from sqlalchemy import create_engine, MetaData, Table, Column, Integer, String, Float, DateTime
from sqlalchemy.orm import declarative_base, sessionmaker, scoped_session



username = 'postgres'
password = 'postgrespassword'
endpoint = 'trading-bot-v1.cnb66avgt4fo.us-east-2.rds.amazonaws.com'
dbName = 'trading_bot_v1'
uri = f'postgresql://{username}:{password}@{endpoint}/{dbName}'

engine = create_engine(uri, pool_size=20, max_overflow=0)
meta = MetaData()

Base = declarative_base()

session_factory = sessionmaker(bind=engine)
Session = scoped_session(session_factory)
dbMain = Session()


class Book(Base):
    '''an instance of a books column. it should hold all data for what happends in that particular timeframe'''
    
    __tablename__ = 'books'

    id = Column(Integer, primary_key=True)
    timestamp = Column(DateTime, nullable=False)
    created_at = Column(DateTime, nullable=False)
    updated_at = Column(DateTime, nullable=False)
    instrument = Column(String, nullable=False)
    granularity = Column(String, nullable=False)
    granularity_seconds = Column(Integer, nullable=False)
    ask = Column(Float, nullable=False)
    bid = Column(Float, nullable=False)
    mid = Column(Float, nullable=False)
    spread = Column(Float, nullable=False)
    open = Column(Float, default=0)
    close = Column(Float, default=0)
    high = Column(Float, default=0)
    low = Column(Float, default=0)
    price_difference = Column(Float, default=0)
    volatility = Column(Float, default=0)
    volume = Column(Float, default=0)
    starting_balance = Column(Float, default=0)
    current_balance = Column(Float, default=0)
    margin_rate = Column(Float, default=0)
    marginable_funds = Column(Float, default=0)
    margin_available = Column(Float, default=0)
    open_trade_count = Column(Integer, default=0)
    open_position_count = Column(Integer, default=0)
    pending_order_count = Column(Integer, default=0)

    day_p_and_l = Column(Float, default=0)
    day_pips = Column(Float, default=0)
    unrealized_p_and_l = Column(Float, default=0)
    unrealized_pips = Column(Float, default=0)
    position = Column(String, default='0')
    avg_entry_price = Column(Float, default=0)
    lots = Column(Float, default=0)
    units = Column(Integer, default=0)
    max_potential_loss = Column(Float, default=0)
    avg_stop_loss = Column(Float, default=0)
    avg_loss_pips = Column(Float, default=0)
    avg_take_profit = Column(Float, default=0)
    take_profit_pips = Column(Float, default=0)
    ma10 = Column(Float, default=0)
    ma25 = Column(Float, default=0)
    ma50 = Column(Float, default=0)
    ma100 = Column(Float, default=0)
    ma200 = Column(Float, default=0)
    ma400 = Column(Float, default=0)
    highest10 = Column(Float, default=0)
    highest25 = Column(Float, default=0)
    highest50 = Column(Float, default=0)
    highest100 = Column(Float, default=0)
    highest200 = Column(Float, default=0)
    highest400 = Column(Float, default=0)
    lowest10 = Column(Float, default=0)
    lowest25 = Column(Float, default=0)
    lowest50 = Column(Float, default=0)
    lowest100 = Column(Float, default=0)
    lowest200 = Column(Float, default=0)
    lowest400 = Column(Float, default=0)
    high_10_percent_10 = Column(Float, default=0)
    high_10_percent_25 = Column(Float, default=0)
    high_10_percent_50 = Column(Float, default=0)
    high_10_percent_100 = Column(Float, default=0)
    high_10_percent_200 = Column(Float, default=0)
    high_10_percent_400 = Column(Float, default=0)
    low_10_percent_10 = Column(Float, default=0)
    low_10_percent_25 = Column(Float, default=0)
    low_10_percent_50 = Column(Float, default=0)
    low_10_percent_100 = Column(Float, default=0)
    low_10_percent_200 = Column(Float, default=0)
    low_10_percent_400 = Column(Float, default=0)

    order_book_up_long_all = Column(Float, default=0)
    order_book_up_short_all = Column(Float, default=0)

    order_book_down_long_all = Column(Float, default=0)
    order_book_down_short_all = Column(Float, default=0)

    order_book_between_long = Column(Float, default=0)
    order_book_between_short = Column(Float, default=0)

    order_book_up_long_0 = Column(Float, default=0)
    order_book_up_short_0 = Column(Float, default=0)
    order_book_up_long_1 = Column(Float, default=0)
    order_book_up_short_1 = Column(Float, default=0)
    order_book_up_long_2 = Column(Float, default=0)
    order_book_up_short_2 = Column(Float, default=0)
    order_book_up_long_3 = Column(Float, default=0)
    order_book_up_short_3 = Column(Float, default=0)
    order_book_up_long_4 = Column(Float, default=0)
    order_book_up_short_4 = Column(Float, default=0)
    order_book_up_long_5 = Column(Float, default=0)
    order_book_up_short_5 = Column(Float, default=0)
    order_book_up_long_6 = Column(Float, default=0)
    order_book_up_short_6 = Column(Float, default=0)
    order_book_up_long_7 = Column(Float, default=0)
    order_book_up_short_7 = Column(Float, default=0)
    order_book_up_long_8 = Column(Float, default=0)
    order_book_up_short_8 = Column(Float, default=0)
    order_book_up_long_9 = Column(Float, default=0)
    order_book_up_short_9 = Column(Float, default=0)
    order_book_up_long_10 = Column(Float, default=0)
    order_book_up_short_10 = Column(Float, default=0)
    order_book_up_long_20 = Column(Float, default=0)
    order_book_up_short_20 = Column(Float, default=0)
    order_book_up_long_40 = Column(Float, default=0)
    order_book_up_short_40 = Column(Float, default=0)
    order_book_up_long_60 = Column(Float, default=0)
    order_book_up_short_60 = Column(Float, default=0)
    order_book_up_long_80 = Column(Float, default=0)
    order_book_up_short_80 = Column(Float, default=0)
    order_book_up_long_100 = Column(Float, default=0)
    order_book_up_short_100 = Column(Float, default=0)

    order_book_down_long_0 = Column(Float, default=0)
    order_book_down_short_0 = Column(Float, default=0)
    order_book_down_long_1 = Column(Float, default=0)
    order_book_down_short_1 = Column(Float, default=0)
    order_book_down_long_2 = Column(Float, default=0)
    order_book_down_short_2 = Column(Float, default=0)
    order_book_down_long_3 = Column(Float, default=0)
    order_book_down_short_3 = Column(Float, default=0)
    order_book_down_long_4 = Column(Float, default=0)
    order_book_down_short_4 = Column(Float, default=0)
    order_book_down_long_5 = Column(Float, default=0)
    order_book_down_short_5 = Column(Float, default=0)
    order_book_down_long_6 = Column(Float, default=0)
    order_book_down_short_6 = Column(Float, default=0)
    order_book_down_long_7 = Column(Float, default=0)
    order_book_down_short_7 = Column(Float, default=0)
    order_book_down_long_8 = Column(Float, default=0)
    order_book_down_short_8 = Column(Float, default=0)
    order_book_down_long_9 = Column(Float, default=0)
    order_book_down_short_9 = Column(Float, default=0)
    order_book_down_long_10 = Column(Float, default=0)
    order_book_down_short_10 = Column(Float, default=0)
    order_book_down_long_20 = Column(Float, default=0)
    order_book_down_short_20 = Column(Float, default=0)
    order_book_down_long_40 = Column(Float, default=0)
    order_book_down_short_40 = Column(Float, default=0)
    order_book_down_long_60 = Column(Float, default=0)
    order_book_down_short_60 = Column(Float, default=0)
    order_book_down_long_80 = Column(Float, default=0)
    order_book_down_short_80 = Column(Float, default=0)
    order_book_down_long_100 = Column(Float, default=0)
    order_book_down_short_100 = Column(Float, default=0)

    position_book_up_long_all = Column(Float, default=0)
    position_book_up_short_all = Column(Float, default=0)

    position_book_down_long_all = Column(Float, default=0)
    position_book_down_short_all = Column(Float, default=0)

    position_book_between_long = Column(Float, default=0)
    position_book_between_short = Column(Float, default=0)

    position_book_up_long_0 = Column(Float, default=0)
    position_book_up_short_0 = Column(Float, default=0)
    position_book_up_long_1 = Column(Float, default=0)
    position_book_up_short_1 = Column(Float, default=0)
    position_book_up_long_2 = Column(Float, default=0)
    position_book_up_short_2 = Column(Float, default=0)
    position_book_up_long_3 = Column(Float, default=0)
    position_book_up_short_3 = Column(Float, default=0)
    position_book_up_long_4 = Column(Float, default=0)
    position_book_up_short_4 = Column(Float, default=0)
    position_book_up_long_5 = Column(Float, default=0)
    position_book_up_short_5 = Column(Float, default=0)
    position_book_up_long_6 = Column(Float, default=0)
    position_book_up_short_6 = Column(Float, default=0)
    position_book_up_long_7 = Column(Float, default=0)
    position_book_up_short_7 = Column(Float, default=0)
    position_book_up_long_8 = Column(Float, default=0)
    position_book_up_short_8 = Column(Float, default=0)
    position_book_up_long_9 = Column(Float, default=0)
    position_book_up_short_9 = Column(Float, default=0)
    position_book_up_long_10 = Column(Float, default=0)
    position_book_up_short_10 = Column(Float, default=0)
    position_book_up_long_20 = Column(Float, default=0)
    position_book_up_short_20 = Column(Float, default=0)
    position_book_up_long_40 = Column(Float, default=0)
    position_book_up_short_40 = Column(Float, default=0)
    position_book_up_long_60 = Column(Float, default=0)
    position_book_up_short_60 = Column(Float, default=0)
    position_book_up_long_80 = Column(Float, default=0)
    position_book_up_short_80 = Column(Float, default=0)
    position_book_up_long_100 = Column(Float, default=0)
    position_book_up_short_100 = Column(Float, default=0)

    position_book_down_long_0 = Column(Float, default=0)
    position_book_down_short_0 = Column(Float, default=0)
    position_book_down_long_1 = Column(Float, default=0)
    position_book_down_short_1 = Column(Float, default=0)
    position_book_down_long_2 = Column(Float, default=0)
    position_book_down_short_2 = Column(Float, default=0)
    position_book_down_long_3 = Column(Float, default=0)
    position_book_down_short_3 = Column(Float, default=0)
    position_book_down_long_4 = Column(Float, default=0)
    position_book_down_short_4 = Column(Float, default=0)
    position_book_down_long_5 = Column(Float, default=0)
    position_book_down_short_5 = Column(Float, default=0)
    position_book_down_long_6 = Column(Float, default=0)
    position_book_down_short_6 = Column(Float, default=0)
    position_book_down_long_7 = Column(Float, default=0)
    position_book_down_short_7 = Column(Float, default=0)
    position_book_down_long_8 = Column(Float, default=0)
    position_book_down_short_8 = Column(Float, default=0)
    position_book_down_long_9 = Column(Float, default=0)
    position_book_down_short_9 = Column(Float, default=0)
    position_book_down_long_10 = Column(Float, default=0)
    position_book_down_short_10 = Column(Float, default=0)
    position_book_down_long_20 = Column(Float, default=0)
    position_book_down_short_20 = Column(Float, default=0)
    position_book_down_long_40 = Column(Float, default=0)
    position_book_down_short_40 = Column(Float, default=0)
    position_book_down_long_60 = Column(Float, default=0)
    position_book_down_short_60 = Column(Float, default=0)
    position_book_down_long_80 = Column(Float, default=0)
    position_book_down_short_80 = Column(Float, default=0)
    position_book_down_long_100 = Column(Float, default=0)
    position_book_down_short_100 = Column(Float, default=0)

Base.metadata.create_all(engine)